basePath: /v1
consumes:
- application/json
host: api.go-template.com
info:
  contact:
    email: ra9dev@gmail.com
    name: ra9dev
    url: https://ra9.dev
  description: go-template based project
  termsOfService: https://github.com/ra9dev/go-template
  title: go-template API
  version: "1.0"
paths: {}
produces:
- application/json
schemes:
- http
- https
securityDefinitions:
  jwt:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
